apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: skaffold-test
build:
  local:
    push: false
  artifacts:
    - image: react-frontend
      context: react-frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'remix-app/app/**/*'
            dest: /remix-app/app
            strip: 'remix-app/app'
    - image: auth-service-img
      context: authservice
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'accounts**/*.py'
            dest: .
          - src: 'authservice**/*.py'
            dest: .
    - image: project-service-img
      context: projectservice
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'teams**/*.py'
            dest: .
          - src: 'projectservice**/*.py'
            dest: .
    # - image: auth-celery
    #   context: authservice
    #   docker:
    #     dockerfile: celery.dockerfile
manifests:
  rawYaml:
    - infra/k8s/react.yaml
    - infra/k8s/authservice.yaml
    - infra/k8s/projectservice.yaml
    - infra/k8s/ingress-rule.yaml
