# Generated by Django 4.2.1 on 2023-08-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='inv_accept',
            new_name='inv_acceptedd',
        ),
    ]
