# Generated by Django 4.2.1 on 2023-06-18 17:58

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists'}, max_length=255, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.ProhibitNullCharactersValidator, django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
