# Generated by Django 4.2.1 on 2023-06-19 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10), django.core.validators.ProhibitNullCharactersValidator, django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^[0-9]+$')]),
        ),
    ]
